/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        neutral: {
          0: '#FFFFFF',
          50: '#F8FAFC',
          100: '#F1F5F9',
          200: '#E2E8F0',
          300: '#CBD5E1',
          400: '#94A3B8',
          500: '#64748B',
          600: '#475569',
          700: '#334155',
          800: '#1E293B',
          900: '#0F172A',
        },
        bg: '#F8FAFC',
        surface: '#FFFFFF',
        'surface-alt': '#F1F5F9',
        border: '#E2E8F0',
        'border-strong': '#CBD5E1',
        text: '#1E293B',
        'text-muted': '#64748B',
        'text-subtle': '#94A3B8',
        primary: '#FF6B9D',
        'primary-hover': '#E85A8A',
        'primary-active': '#D14979',
        'primary-subtle': '#FFF1F5',
        secondary: '#c44dff',
        accent: '#ffd93d',
        success: '#22C55E',
        'success-subtle': '#F0FDF4',
        warning: '#F59E0B',
        'warning-subtle': '#FFFBEB',
        danger: '#EF4444',
        'danger-subtle': '#FEF2F2',
        info: '#3B82F6',
        'info-subtle': '#EFF6FF',
      },
      fontFamily: {
        display: ['var(--font-display)', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(15, 23, 42, 0.06)',
        md: '0 2px 8px rgba(15, 23, 42, 0.08), 0 1px 2px rgba(15, 23, 42, 0.04)',
        lg: '0 8px 24px rgba(15, 23, 42, 0.12), 0 2px 6px rgba(15, 23, 42, 0.06)',
      },
      transitionDuration: {
        fast: '120ms',
        base: '200ms',
        slow: '320ms',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'flash': 'flash 0.3s ease-out',
        'confetti': 'confetti 1s ease-out',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { transform: 'translateY(20px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        scaleIn: { '0%': { transform: 'scale(0.9)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        flash: { '0%': { opacity: '0' }, '50%': { opacity: '1' }, '100%': { opacity: '0' } },
        confetti: { '0%': { transform: 'translateY(0) rotate(0deg)', opacity: '1' }, '100%': { transform: 'translateY(-100px) rotate(720deg)', opacity: '0' } },
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
